site_name: 3D City Database v5 documentation
site_url: https://otherdocs.brunowillenborg.de/
site_description: Notizen und Dokumentation zu Meetings
site_author: 3DCityDB Steering Group
copyright: 3DCityDB Steering Group, 2025
repo_name: bwibo/3dcitydb-mkdocs
repo_url: https://github.com/bwibo/3dcitydb-mkdocs
edit_uri: edit/main/docs

# Page tree ###################################################################
# nav:

# Theme #######################################################################
theme:
  name: material
  language: en
  logo: ./assets/img/logos/3dcitydb-logo-transparent.png
  favicon: ./assets/img/logos/3dcitydb-logo-transparent.png
  palette:
  # font:
  #   # text: IBM Plex Sans
  #   text: Inter
  #   # code: DM Mono
  # Palette toggle for light mode
  - scheme: default
    primary: green
    accent: cyan
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    primary: green
    accent: cyan
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    # Navigation
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    # - navigation.instant.preview
    # Code
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Header
    - header.autohide
    # Content tabs
    - content.tabs.link

# Plugins #####################################################################
plugins:
  - search:
      lang: en
  - glightbox
  - awesome-pages
  - tags:
      tags: true
  - mike:
      # alias_type: copy
      # canonical_version: latest
      css_dir: assets/stylesheets
      javascript_dir: assets/javascripts
      # # deploy_prefix: /3dcitydb-mkdocs
      # version_selector: true

# Extra #######################################################################
extra:
  homepage: https://github.com/3dcitydb/3dcitydb-mkdocs
  status:
    wip: "Work in progress"
  version:
    provider: mike
    # default: latest

# Markdown extensions #########################################################
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
      title: Table of content
      toc_depth: 3
      permalink_title: Link to this headline for referencing
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

# Extra js ####################################################################
extra_javascript:
  - assets/javascripts/tablesort.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/contrib/auto-render.min.js

# Extra CSS ###################################################################
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css
  - assets/stylesheets/extra.css

watch:
  - includes
