site_name: 3D City Database v5 documentation
site_url: https://docs.brunowillenborg.de/
site_description: Documentation for the 3D City Database v5.
site_author: 3DCityDB Steering Group
copyright: 3DCityDB Steering Group, 2025
repo_name: bwibo/3dcitydb-mkdocs
repo_url: https://github.com/BWibo/3dcitydb-mkdocs
edit_uri: edit/main/docs

# Page tree ###################################################################
nav:
  - Welcome:
    - index.md
    - download.md
    - compatibility.md
    - usage-contrib.md
    - tags.md
  - First steps:
    - first-steps/index.md
    - first-steps/requirements.md
    - first-steps/setup.md
    - first-steps/citydb-tool.md
    - first-steps/docker.md
    - first-steps/migration.md
  - 3D City Database:
    - 3dcitydb/index.md
    - Relational schema:
      - Schema overview: 3dcitydb/relational-schema.md
      - Feature module: 3dcitydb/feature-module.md
      - Geometry module: 3dcitydb/geometry-module.md
      - Appearance module: 3dcitydb/appearance-module.md
      - Metadata module: 3dcitydb/metadata-module.md
      - Codelist module: 3dcitydb/codelist-module.md
    - 3dcitydb/db-scripts.md
    - 3dcitydb/db-functions.md
    - 3dcitydb/db-upgrade.md
    - 3dcitydb/docker.md
  - citydb-tool:
    - citydb-tool/index.md
    - citydb-tool/cli.md
    - citydb-tool/database.md
    - citydb-tool/connect.md
    - citydb-tool/info.md
    - Import command:
      - Import overview: citydb-tool/import.md
      - CityGML import: citydb-tool/import-citygml.md
      - CityJSON import: citydb-tool/import-cityjson.md
    - Export command:
      - Export overview: citydb-tool/export.md
      - CityGML export: citydb-tool/export-citygml.md
      - CityJSON export: citydb-tool/export-cityjson.md
    - citydb-tool/delete.md
    - citydb-tool/index-command.md
    - JSON configuration:
      - Configuration overview: citydb-tool/config.md
      - Import configuration: citydb-tool/import-config.md
      - Export configuration: citydb-tool/export-config.md
      - Delete configuration: citydb-tool/delete-config.md
      - Report configuration: citydb-tool/report-config.md
    - citydb-tool/cql2.md
    - citydb-tool/docker.md
  - Contributors:
    - contributors/index.md
    - contributors/tum-gis.md
    - contributors/hft-stuttgart.md
    - contributors/list-eco.md
    - contributors/moss.md
    - contributors/vcs.md
    - contributors/acknowledgements.md

# Theme #######################################################################
theme:
  name: material
  language: en
  logo: ./assets/img/logos/3dcitydb-logo-transparent.png
  favicon: ./assets/img/logos/3dcitydb-logo-transparent.png
  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: green
    accent: cyan
    media: "(prefers-color-scheme: light)"
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    primary: green
    accent: cyan
    media: "(prefers-color-scheme: dark)"
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
    # Navigation
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    # Code
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Header
    - header.autohide
    # Content tabs
    - content.tabs.link

# Plugins #####################################################################
plugins:
  - tags:
      tags: true

# Extra #######################################################################
extra:
  homepage: https://github.com/3dcitydb/
  status:
    wip: "Work in progress"
  version:
    provider: mike
    default: latest
    alias: true

# Markdown extensions #########################################################
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - toc:
      permalink: true
      title: Table of content
      toc_depth: 3
      permalink_title: Link to this headline for referencing
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

# Extra js ####################################################################
extra_javascript:
  - assets/javascripts/tablesort.js
  - https://cdn.jsdelivr.net/npm/tablesort@5.3.0/dist/tablesort.min.js
  - assets/javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/contrib/auto-render.min.js

# Extra CSS ###################################################################
extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css
  - assets/stylesheets/extra.css
