name: Deploy MkDocs Docs - edge

on:
  push:
    branches: [main]

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    # concurrency:
    #   group: docs-deploy
    #   cancel-in-progress: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for mike to access full git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -U -r requirements.txt

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Deploy documentation
        run:
          mike deploy --push --update-aliases edge
