name: Deploy MkDocs Docs - Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Match version tags like v1.0, v2.1.3

permissions:
  contents: write  # Required to push to gh-pages

jobs:

  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: docs-deploy
      cancel-in-progress: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for mike to access full git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -U -r requirements.txt

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Deploy edge version
        run:
          mike deploy --push --update-aliases edge

      - name: Deploy release version
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mike deploy --push --update-aliases edge
          mike deploy --push --update-aliases "$VERSION" latest
          mike set-default --push latest
