name: Deploy MkDocs Docs

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Match version tags like v1.0, v2.1.3

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: docs-deploy
      cancel-in-progress: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for mike to access full git history

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -U -r requirements.txt

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Deploy documentation
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            mike deploy --push --update-aliases "$VERSION" latest
            mike set-default --push latest
          elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            mike deploy --push --update-aliases edge
          fi
